## LIBRARIES
it is a set of function, modules, and classes where it has some pre-written codes to perform some tasks

## 1.PANDAS LIBRARY

- For Data Analysis

In [2]:
import pandas as pd #ALIAS

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\shaha\appdata\local\programs\python\python310\lib\site-packages (2.3.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.22.4 in c:\users\shaha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shaha\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shaha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shaha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\shaha\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
pd.read_csv(filepath_or_buffer = r"D:\Data_Science\insurance.csv")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
insurance_charges = pd.read_csv(filepath_or_buffer = "insurance.csv")

In [6]:
insurance_charges

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
df = pd.read_csv("insurance.csv")

In [8]:
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [10]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [12]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

df.index

In [15]:
df["age"]

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [17]:
len(df["age"])

1338

In [18]:
df[["age" , "bmi"]]

      age     bmi
0      19  27.900
1      18  33.770
2      28  33.000
3      33  22.705
4      32  28.880
...   ...     ...
1333   50  30.970
1334   18  31.920
1335   18  36.850
1336   21  25.800
1337   61  29.070

[1338 rows x 2 columns]

In [19]:
df.iloc[0]

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
charges     16884.924
Name: 0, dtype: object

In [20]:
df.iloc[2]

age                28
sex              male
bmi              33.0
children            3
smoker             no
region      southeast
charges      4449.462
Name: 2, dtype: object

In [24]:
df.iloc[1300]

age                  45
sex                male
bmi               30.36
children              0
smoker              yes
region        southeast
charges     62592.87309
Name: 1300, dtype: object

In [26]:
df.iloc[1324]["sex"]

'male'

In [36]:
df[(df["sex"] == "female")&(df["age"] == 19)]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
32     19  female  28.600         5     no  southwest   4687.79700
65     19  female  28.900         0     no  southwest   1743.21400
106    19  female  28.400         1     no  southwest   2331.51900
126    19  female  28.300         0    yes  southwest  17081.08000
168    19  female  31.825         1     no  northwest   2719.27975
200    19  female  32.110         0     no  northwest   2130.67590
232    19  female  17.800         0     no  southwest   1727.78500
311    19  female  24.700         0     no  southwest   1737.37600
362    19  female  21.700         0    yes  southwest  13844.50600
391    19  female  37.430         0     no  northwest   2138.07070
414    19  female  35.150         0     no  northwest   2134.90150
472    19  female  29.800         0     no  southwest   1744.46500
490    19  female  32.900         0     no  southwest   1748.77400
526    19  female  30.590         2     no  northwest  24059.68019
565    19  female  30.495         0     no  northwest   2128.43105
604    19  female  28.310         0    yes  northwest  17468.98390
618    19  female  33.110         0    yes  southeast  34439.85590
636    19  female  24.510         1     no  northwest   2709.11190
773    19  female  28.880         0    yes  northwest  17748.50620
807    19  female  36.575         0     no  northwest   2136.88225
899    19  female  22.515         0     no  northwest   2117.33885
926    19  female  23.400         2     no  southwest   2913.56900
960    19  female  39.615         1     no  northwest   2730.10785
973    19  female  40.500         0     no  southwest   1759.33800
1016   19  female  24.605         1     no  northwest   2709.24395
1129   19  female  18.600         0     no  southwest   1728.89700
1139   19  female  32.490         0    yes  northwest  36898.73308
1195   19  female  27.930         3     no  northwest  18838.70366
1196   19  female  30.020         0    yes  northwest  33307.55080
1299   19  female  25.745         1     no  northwest   2710.82855
1313   19  female  34.700         2    yes  southwest  36397.57600
1316   19  female  20.600         0     no  southwest   1731.67700

In [37]:
df[df["bmi"] > 33]

      age     sex     bmi  children smoker     region      charges
1      18    male  33.770         1     no  southeast   1725.55230
6      46  female  33.440         1     no  southeast   8240.58960
12     23    male  34.400         0     no  southwest   1826.84300
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
...   ...     ...     ...       ...    ...        ...          ...
1325   61    male  33.535         0     no  northeast  13143.33665
1329   52    male  38.600         2     no  southwest  10325.20600
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1335   18  female  36.850         0     no  southeast   1629.83350

[456 rows x 7 columns]

In [38]:
df[df["region"].str.startswith("n")]

      age     sex     bmi  children smoker     region      charges
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
...   ...     ...     ...       ...    ...        ...          ...
1326   42  female  32.870         0     no  northeast   7050.02130
1328   23  female  24.225         2     no  northeast  22395.74424
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1337   61  female  29.070         0    yes  northwest  29141.36030

[649 rows x 7 columns]

In [41]:
df[df["age"].astype(str).str.endswith("2")]

      age     sex     bmi  children smoker     region      charges
4      32    male  28.880         0     no  northwest   3866.85520
11     62  female  26.290         0    yes  southeast  27808.72510
16     52  female  30.780         1     no  northeast  10797.33620
30     22    male  35.600         0    yes  southwest  35585.57600
36     62  female  32.965         3     no  northwest  15612.19335
...   ...     ...     ...       ...    ...        ...          ...
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1326   42  female  32.870         0     no  northeast   7050.02130
1329   52    male  38.600         2     no  southwest  10325.20600
1332   52  female  44.700         3     no  southwest  11411.68500

[133 rows x 7 columns]

In [42]:
df[df["region"].isin(["northwest"])]

      age     sex     bmi  children smoker     region      charges
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
7      37  female  27.740         3     no  northwest   7281.50560
9      60  female  25.840         0     no  northwest  28923.13692
24     37    male  28.025         2     no  northwest   6203.90175
...   ...     ...     ...       ...    ...        ...          ...
1319   39  female  26.315         2     no  northwest   7201.70085
1320   31    male  31.065         3     no  northwest   5425.02335
1324   31    male  25.935         1     no  northwest   4239.89265
1333   50    male  30.970         3     no  northwest  10600.54830
1337   61  female  29.070         0    yes  northwest  29141.36030

[325 rows x 7 columns]

In [43]:
df.loc[df["smoker"] == "yes"]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
11     62  female  26.290         0    yes  southeast  27808.72510
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
...   ...     ...     ...       ...    ...        ...          ...
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1321   62    male  26.695         0    yes  northeast  28101.33305
1323   42  female  40.370         2    yes  southeast  43896.37630
1337   61  female  29.070         0    yes  northwest  29141.36030

[274 rows x 7 columns]

In [44]:
df["sex"] = df["sex"].str.upper()

In [47]:
df["sex"]

0       FEMALE
1         MALE
2         MALE
3         MALE
5       FEMALE
         ...
1333      MALE
1334    FEMALE
1335    FEMALE
1336    FEMALE
1337    FEMALE
Name: sex, Length: 1337, dtype: object

In [46]:
df = df.drop(4)

In [48]:
df

      age     sex     bmi  children smoker     region      charges
0      19  FEMALE  27.900         0    yes  southwest  16884.92400
1      18    MALE  33.770         1     no  southeast   1725.55230
2      28    MALE  33.000         3     no  southeast   4449.46200
3      33    MALE  22.705         0     no  northwest  21984.47061
5      31  FEMALE  25.740         0     no  southeast   3756.62160
...   ...     ...     ...       ...    ...        ...          ...
1333   50    MALE  30.970         3     no  northwest  10600.54830
1334   18  FEMALE  31.920         0     no  northeast   2205.98080
1335   18  FEMALE  36.850         0     no  southeast   1629.83350
1336   21  FEMALE  25.800         0     no  southwest   2007.94500
1337   61  FEMALE  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [51]:
df.dropna()
df.fillna(0, inplace=True)

In [52]:
df

      age     sex     bmi  children smoker     region      charges
0      19  FEMALE  27.900         0    yes  southwest  16884.92400
1      18    MALE  33.770         1     no  southeast   1725.55230
2      28    MALE  33.000         3     no  southeast   4449.46200
3      33    MALE  22.705         0     no  northwest  21984.47061
5      31  FEMALE  25.740         0     no  southeast   3756.62160
...   ...     ...     ...       ...    ...        ...          ...
1333   50    MALE  30.970         3     no  northwest  10600.54830
1334   18  FEMALE  31.920         0     no  northeast   2205.98080
1335   18  FEMALE  36.850         0     no  southeast   1629.83350
1336   21  FEMALE  25.800         0     no  southwest   2007.94500
1337   61  FEMALE  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [ ]:
pd.read_csv(filepath_or_buffer = "insurance.csv")